test:
    build: .
    dockerfile: typescript/test/Dockerfile
    environment:
        PORT: 3000
        TOKEN_SECRET: "this is a secret"
        RESET_PASSWORD_TOKEN_SECRET: "this is a reset password secret"
        NODE_ENV: "development"
        RDS_PORT: "5432"
        RDS_USERNAME: "docker"
        RDS_PASSWORD: ""
        RDS_HOSTNAME: "postgres"
        RDS_DB_NAME: "test"
        EMAIL_HOST: "localhost"
        EMAIL_PASSWORD: "email password"
        EMAIL_USERNAME: "email username"
        EMAIL_PORT: 1231
        EMAIL_FROM: "testing@66pix.com"
        AWS_S3_KEY: "fake-key"
        AWS_S3_SECRET: "fake-secret"
        AWS_S3_BUCKET: "fake-bucket"
        AWS_S3_REGION: "us-east-1"
        AWS_SQS_DOWNLOAD_ID: "123"
        AWS_SQS_DOWNLOAD_SECRET: "123"
        AWS_SQS_DOWNLOAD_REGION: "us-east-2"
        AWS_SQS_DOWNLOAD_URL: "123"
        CDN_URL: "//images.cdn.staging.66pix.com"
        PRODUCT_CODE_SALT: "PRODUCT_CODE_SALT"
        BASE_URL: "https://staging.66pix.com"
        BRAINTREE_MERCHANT_ID: "v3727swzz6d3zbkq"
        BRAINTREE_PRIVATE_KEY: "4cb9faff1c31f70519b5400699e8423a"
        BRAINTREE_PUBLIC_KEY: "jwg9gs4hjwb4kfnw"
    links:
        - postgres
    volumes:
        - .:/srv/www
    dns:
        - 8.8.8.8
        - 9.9.9.9

postgres:
    image: postgres
    ports:
        - "5342"
    environment:
        POSTGRES_USER: "docker"


