FROM node:7

ARG NPM_TOKEN

ENV TZ=Pacific/Auckland
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
RUN echo "deb http://apt.dockerproject.org/repo debian-jessie main" >> /etc/apt/sources.list.d/docker.list

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-pip docker docker-engine postgresql zip python-dev yarn

ENV NODE_ENV="development"
RUN npm install --silent -g typescript tslint nsp

COPY ./test-helpers/.npmrc /tmp/.npmrc
ADD package.json /tmp/package.json
ADD yarn.lock /tmp/yarn.lock
RUN cd /tmp && yarn
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/
RUN rm -f .npmrc

WORKDIR /opt/app
ADD . /opt/app

CMD /opt/app/test-lambci.sh
