test:
    build: .
    dockerfile: test/Dockerfile
    environment:
        PORT: 3000
        TOKEN_SECRET: "this is a secret"
        RESET_PASSWORD_TOKEN_SECRET: "this is a reset password secret"
        NODE_ENV: "development"
        RDS_PORT: "5432"
        RDS_USERNAME: "docker"
        RDS_PASSWORD: ""
        RDS_HOSTNAME: "postgres"
        RDS_DB_NAME: "test"
    links:
        - postgres
    volumes:
        - .:/srv/www
    dns:
        - 8.8.8.8
        - 9.9.9.9

postgres:
    image: postgres
    ports:
        - "5342"
    environment:
        POSTGRES_USER: "docker"


